export const Local = {
    alert: {
        title: {
            information: "Bilgilendirme Mesajı"
        },
        centered_alert_two_buttons: {
            title: "Emin Misiniz?",
            title_confirm: 'İşlem Onayı',
            confirm_text: "Tamam",
            cancel_text: "İptal",
            save_question: "Değişiklikleri kaydetmek istiyor musunuz?",
            irreversible_action: "Bu işlem geri alınamayan bir işlemdir."
        },
        top_alert: {
            inform: 'Lütfen bilgileri eksiksiz giriniz!',
            success: 'İşlem başarıyla tamamlandı!'
        }
    },
    form_info: {
        full_name: 'Ad Soyad',
        full_name_upper: 'AD SOYAD',
        name: 'Ad',
        surname: 'Soyad',
        email: "E-Posta Adresi",
        other_email: "Diğer E-Posta Adresi",
        corporate_email: 'Kurumsal E-Posta Adresi',
        phone_number: "Telefon Numarası",
        choose_brand: "Marka Seçiniz",
        choose_gender: 'Cinsiyet Seçiniz',
        choose_status: 'Durum Seçiniz',
        choose_teacher: 'Eğitmen Seçiniz',
        choose_marital_status: 'Medeni Hal Seçiniz',
        job: 'Meslek',
        choose_job: 'Meslek Seçiniz',
        birth_date: 'Doğum Tarihi',
        birth_date_upper: 'DOĞUM TARİHİ',
        birth_place: 'Doğum Yeri',
        birth_place_upper: 'DOĞUM YERİ',
        gender: 'Cinsiyet',
        gender_upper: 'CİNSİYET',
        date_placeholder: 'gg/aa/yyyy',
        profile_photo: 'Profil Resmi',
        work_start_date: 'İşe Başlama Tarihi',
        work_start_date_upper: 'İŞE BAŞLAMA TARİHİ',
        end_date: 'İşten Ayrılma Tarihi',
        work_end_date_upper: 'İŞTEN AYRILMA TARİHİ',
        status: 'Durum',
        status_upper: 'DURUM',
        marital_status: 'Medeni Hali',
        marital_status_upper: 'MEDENİ HALİ',
        image_name: 'Profil Fotoğrafı İsmi',
        image_name_upper: 'PROFİL FOTOĞRAFI İSMİ',
        sound_name: "Ses Kaydı İsmi",
        sound_name_upper: "SES KAYDI İSMİ",
        tooltip_profile: "Örnek Profil Fotoğrafı İsmi: 8051.profile.jpg",
        tooltip_sound: "Örnek Ses Kaydı İsmi: 1029.webm.mp3",
        university: 'Üniversite Adı',
        university_upper: 'ÜNİVERSİTE ADI',
        department: 'Bölüm',
        department_upper: 'BÖLÜM',
        about: 'Hakkında',
        teacher_id_upper: 'EĞİTMEN ID',
        about_upper: 'HAKKINDA',
        days: 'Günler',
        start_end_date: 'Başlangıç Bitiş Tarihi',
        start_end_date_hour: 'Başlangıç Bitiş Saati',
        start_date: 'Başlangıç Tarihi',
        yes: 'Evet',
        no: 'Hayır',
        description: 'Açıklama',
        active: 'Aktif',
        pasive: 'Pasif',
        removed: 'Kaldırıldı',
        title: 'Ünvan',
        city: 'Şehir',
        male: 'Erkek',
        female: 'Kadın',
        undefined: 'Belirtilmedi',
        validity_date: 'Geçerlilik Tarihi'
    },
    count: '<span class="font-bold">#count#</span> adet kayıt bulundu.',
    detail_search_titles: {
        detail_search: 'Detaylı Arama',
        students: 'Tüm Öğrenciler',
        teachers: 'Tüm Eğitmenler',
        status: 'Tüm Durumlar',
        begin_end_hours: 'Tüm Başlangıç / Bitiş Saatleri',
        begin_time: 'Başlangıç Saati',
        end_time: 'Bitiş Saati',
        choose_all: 'Tümünü Seç',
        minutes: 'Tüm Dakikalar',
        discounts: 'Tüm İndirimler',
        week_days: 'Tüm Günler',
        search_teacher: 'Eğitmen Ara',
        selected_data_count: 'Seçilen Veri Sayısı',
    },
    button: {
        save: 'Kaydet',
        save_upper: 'KAYDET',
        cancel: 'İptal',
        cancel_upper: 'İPTAL',
        confirm: 'Onayla',
        confirm_upper: 'ONAYLA',
        create: 'Oluştur',
        clear: 'Temizle',
        update: 'Güncelle',
        update_upper: 'GÜNCELLE',
        add: 'Ekle',
        add_upper: 'EKLE',
        delete: 'Sil',
        undo: 'Geri Al',
        send: 'Gönder',
        list: 'Listele',
        browse: "Göz at",
        choose: 'Seç',
        choose_upper: 'SEÇ',
        list_upper: 'LİSTELE',
        edit: 'Düzenle',
        continue: 'Devam Et',
    },
    search_bar: {
        search: 'Ara',
        clear: 'Temizle'
    },
    pagination: {
        previous: "Geri",
        next: "İleri"
    },
    table: {
        profile_photo: 'Profil Resmi',
        profile: 'Profil',
        employee_informations: 'Kullanıcı Bilgileri',
        corparate_informations: 'Kurumsal Bilgiler',
        teacher_informations: 'Eğitmen Bilgileri',
        working_hours: 'Çalışma Saatleri',
        working_informations: 'Çalışma Bilgileri',
        date: 'Tarih',
        operation: 'İşlem',
        hour: 'Saat',
        duration: 'Süre',
        minute: 'Dakika',
        minutes: 'Dakikalar',
    },
    errors: {
        //genel hatalar
        title: "Hata",
        an_error_occurred: "İşlem başarısız oldu!",
        not_authorized: "Yetkiniz yok",
        no_records_found: "Herhangi Bir Kayıt Bulunamadı",
        not_authorized_for_this_page: "Bu sayfaya giriş için yetkiniz yok",
        not_allowed: "İşleme Kapalı",
        it_is_not_specified: "Belirtilmedi",
        it_is_not_specified_upper: 'BELİRTİLMEDİ',
        error404_title: "Sayfa Bulunamadı",
        error404_content: "Aradığınız sayfa bulunamadı. Menüleri kullanarak dilediğiniz sayfaya ulaşabilirsiniz.",
        //.... alanı gereklidir hataları
        email_error: "E-posta Adresi alanı gereklidir!",
        code_error: "Doğrulama kodu alanı gereklidir!",
        password_error: "Şifre alanı gereklidir!",
        passwords_cannot_be_different: "Şifreler aynı olmalıdır!",
        //format uygun değil hataları
        email_format_error: "E-mail formatı uygun değil.",
        phone_number_format_error: "Telefon numarası formatı uygun değil.",
        identity_number_format_error: 'TC kimlik numarası formatı uygun değil.',
        //.... boş geçilemez hataları
        general_null_error: 'Bu alan boş geçilemez',
        teacher_id_null_error: 'Eğitmen Id alanı boş geçilemez.',
        full_name_null_error: "Ad soyad alanı boş geçilemez.",
        birth_date_null_error: 'Doğum tarihi alanı boş geçilemez.',
        gender_null_error: 'Cinsiyet alanı boş geçilemez.',
        start_date_null_error: 'Başlangıç tarihi alanı boş geçilemez.',
        teacher_null_error: 'Eğitmen alanı boş geçilemez.',
        week_days_null_error: 'Gün seçimi alanı boş geçilemez.',
        time_range_null_error: 'Saat aralığı alanı boş geçilemez.',
        minute_null_error: 'Dakika alanı boş geçilemez.',
        status_null_error: 'Durum bilgisi alanı boş geçilemez.',
    },
    loading: "Yükleniyor",
    sidebar: {
        home_page: "Ana Sayfa",
        profile: {
            my_profile: "Profilim",
            logout: "Çıkış Yap"
        },
        teacher: {
            title: "Eğitmen İşlemleri",
            list: "Eğitmenler",
            add_teacher: "Eğitmen Ekle",
            teacher_program: "Eğitmen Programı",
        },
    },
    navbar: {
        search: "Ara ...",
    },
    auth: {
        login: {
            title: "Giriş",
            your_email: "E-posta Adresi",
            your_password: "Şifre",
            forgot_password: "Şifremi Unuttum",
            login_button: "Giriş Yap",
        },
        forgot_password: {
            title: "Şifremi Unuttum",
            your_email: "Kurumsal E-Posta Adresiniz",
            button: "Doğrulama Kodu Gönder",
            login: "Giriş Yap",
        },
        verify_code: {
            title: "Şifremi Unuttum",
            your_code: "Doğrulama Kodunu Giriniz",
            button: "Kontrol Et",
            login: "Giriş Yap",
        },
        update_password: {
            title: "Şifremi Güncelle",
            your_password: "Yeni Şifreniz",
            your_password2: "Yeni Şifreniz (Tekrar)",
            button: "Şifremi Güncelle",
            login: "Giriş Yap",
            success: {
                title: "İşlem Başarılı",
                message: "Şifreniz başarıyla değiştirilmiştir.",
            }
        },
    },
    dashboard: {
        welcome: "Hoşgeldin"
    },
    teacher: {
        teacher_title: 'Eğitmen',
        teacher_list: {
            search_text: 'Eğitmen aramak için eğitmen ismi giriniz',
            detail: 'Detay',
            education_program: 'Eğitim Programı',
            start_date_upper: 'BAŞLANGIÇ TARİHİ',
            end_date_upper: 'ÇIKIŞ TARİHİ',
            move_students: 'Öğrencileri Taşı',
        },
        teacher_program: {
            lesson_text: '<span class=\"text-green\">Ders</span>',
            empty_text: '<span class=\"text-blue\">Boş</span> ',
            blocked_text: '<span class=\"text-warning\">Bloke</span>',
            holiday_text: '<span class=\"text-[#6861ce]\">Tatil</span>',
            temporary_blocked_text: '<span class=\"text-red\">Geçiçi Bloke</span>',
            missed_call_text: '<span class=\"text-danger\">Dersini Kaçırmış</span>',
            missed_lesson: 'Dersi Kaçırdı',
            dont_call: 'Aranmadım',
            postponed: 'Erteledi',
            lesson_blocked: 'Eğitmenin bu saat aralığı siz kaldırana kadar bloke edilecektir.',
            lesson_temprorary_blocked: 'Eğitmenin bu saat aralığı sadece #lessonDay# tarihine kadar bloke edilecektir.',
            blocked: 'Bloke',
            temporary_blocked: 'Geçiçi Bloke',
            blocked_temprorary_blocked: 'Bloke / Geçiçi Bloke Et',
            weekly_lesson_count: 'Haftalık Ders Sayısı',
            lesson_time: 'Ders Süresi',
            remaining_lesson_count: 'Kalan Ders Sayısı',
            select_teacher_to_see: 'Eğitmen Programını Görüntülemek İçin Bir Eğitmen Seçiniz',
            shift_not_found: 'Eğitmen Çalışma Saati Bulunamadı',
            days: {
                monday: 'Pazartesi',
                tuesday: 'Salı',
                wednesday: 'Çarşamba',
                thursday: 'Perşembe',
                friday: 'Cuma',
                saturday: 'Cumartesi',
                sunday: 'Pazar'
            }
        },
        create_teacher: {
            personal_informations: 'Kişisel Bilgiler',
            working_hours: 'Çalışma Saatleri',
            call_address: 'Arama Adresleri',
            areas_of_interest: 'İlgi Alanları',
            create_teacher_success_message: 'Eğitmen oluşturma başarıyla tamamlandı!',
            create_interests_success_message: 'İlgi alanları başarıyla eklendi!',
            create_shift_success_message: 'Çalışma saati başarıyla eklendi!',
            select_start_end_hour: 'Başlangıç/Bitiş Saati',
            delete_shift_success_message: 'Çalışma saati başarıyla silindi!',
            sound_record: 'Ses Kaydı'
        },
        update_teacher: {
            teacher_update_success_message: 'Eğitmen başarıyla güncellendi!',
            update_teacher: 'Eğitmen Güncelle',
            areas_of_interests_success_message: 'İlgi alanları başarıyla güncellendi!',
            update_shift_success_message: 'Çalışma saati başarıyla güncellendi!',
            shift_not_found: 'Çalışma Saati Bulunamadı',
            add_new_shift: 'Yeni Çalışma Saati Ekle',
        },
        detail: {
            teacher_details: "Eğitmen Detayları"
        },
        move_student: {
            move_students: 'Öğrencileri Taşı',
            students: 'Öğrenciler',
            search_student: "Öğrenci Ara",
            student_moved_success_message: 'Student #studentName# başarıyla taşındı!',
            students_moved_success_message: 'Öğrenciler başarıyla taşındı!',
            avaliable_teacher_not_found: 'Uygun eğitmen bulunamadı!',
        },
        add_break: {
            block_success_message: 'Çalışma saati başarıyla bloke edildi!',
            temporary_block_success_message: 'Çalışma saati başarıyla geçiçi olarak bloke edildi!',
            block_delete_confirm_question: 'Blokeyi silmek istediğinize emin misiniz?',
            temporary_block_delete_confirm_question: 'Geçiçi blokeyi silmek istediğinize emin misiniz?',
            block_delete_success_message: 'Bloke başarıyla silindi!',
            temporary_block_delete_success_message: 'Geçiçi bloke başarıyla silindi!',
        }
    }
}